# Generated by Django 5.2.3 on 2025-08-24 03:28

import phonenumber_field.modelfields
import tinymce.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Future_Of_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(error_messages={'unique': 'Email Address already exists.'}, max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Phone number already exists.'}, max_length=128, region=None, unique=True)),
                ('course_type', models.CharField(choices=[('', 'Select course type...'), ('web3', 'Web3 Fundamentals'), ('dao', 'DAO Governance'), ('metaverse', 'Metaverse Collaboration'), ('blockchain', 'Blockchain Development')], default='', max_length=20)),
                ('plan_preference', models.CharField(choices=[('', 'Select plan...'), ('basic', 'Basic Plan'), ('pro', 'Pro Plan'), ('exclusive', 'Exclusive')], default='', max_length=20)),
                ('expertise', models.CharField(choices=[('', 'Select your level...'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('gateway', models.CharField(blank=True, choices=[('helio', 'Helio'), ('remita', 'Remita'), ('opay', 'OPay')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
