# Generated by Django 5.2.3 on 2025-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='future_of_work',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
