# Generated by Django 5.2.2 on 2025-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='visit_count',
        ),
    ]
