# Generated by Django 5.2.7 on 2025-10-09 01:03

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', tinymce.models.HTMLField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailApp.subscriber')),
            ],
        ),
    ]
