# Generated by Django 5.2.7 on 2025-10-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0002_personalizedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WhatsappContact',
        ),
        migrations.DeleteModel(
            name='WhatsappMessage',
        ),
    ]
