# Generated by Django 5.2.3 on 2025-08-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0002_future_of_work_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='future_of_work',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
