# Generated by Django 5.2.2 on 2025-08-05 13:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0002_sitestats_remove_subscriber_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
