# Generated by Django 5.2.7 on 2025-10-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0003_telegramcampaign_telegramsubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramcampaign',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramcampaign',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramcampaign',
            name='total_subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
